// grab save
console.log(localStorage.getItem("local_game_saved"))
console.log(localStorage.getItem("local_have_potato"))
console.log(localStorage.getItem("local_potato_tier"))
console.log(localStorage.getItem("local_max_potato_tier"))
console.log(localStorage.getItem("local_study_progress"))
console.log(localStorage.getItem("local_seeds")) // we give a seed back if a potato was planted
console.log(localStorage.getItem("local_potato_dna"))
console.log(localStorage.getItem("local_coins"))
console.log(localStorage.getItem("local_coins_per_second"))
console.log(localStorage.getItem("local_dna_upgrade_seeds_level"))
console.log(localStorage.getItem("local_dna_upgrade_seeds_cost"))
console.log(localStorage.getItem("local_dna_upgrade_speed_level"))
console.log(localStorage.getItem("local_dna_upgrade_speed_cost"))
console.log(localStorage.getItem("local_potato_stage_requirement"))
console.log(localStorage.getItem("local_achievements"))
console.log(localStorage.getItem("local_auto_seeder"))
console.log(localStorage.getItem("local_auto_planter"))
console.log(localStorage.getItem("local_auto_harvest"))
console.log(localStorage.getItem("local_fertilizer_level"))
console.log(localStorage.getItem("local_fertilizer_price"))
console.log(localStorage.getItem("local_seed_research_cost"))
console.log(localStorage.getItem("local_mashed_potatoes"))
console.log(localStorage.getItem("local_baked_potato_boost"))
console.log(localStorage.getItem("local_study_req"))
console.log(localStorage.getItem("local_study_req_cost"))
console.log("game save grabbed")
// set save
localStorage.setItem("local_game_saved",true)
localStorage.setItem("local_have_potato",Number(have_potato))
localStorage.setItem("local_potato_tier",potato_tier)
localStorage.setItem("local_max_potato_tier",max_potato_tier)
localStorage.setItem("local_study_progress",study_progress)
localStorage.setItem("local_seeds",seeds + Number(potato_planted)) // we give a seed back if a potato was planted
localStorage.setItem("local_potato_dna",potato_dna)
localStorage.setItem("local_coins",coins)
localStorage.setItem("local_coins_per_second",coins_per_second)
localStorage.setItem("local_dna_upgrade_seeds_level",seed_upgrade_level)
localStorage.setItem("local_dna_upgrade_seeds_cost",seed_upgrade_cost)
localStorage.setItem("local_dna_upgrade_speed_level",speed_upgrade_level)
localStorage.setItem("local_dna_upgrade_speed_cost",speed_upgrade_cost)
localStorage.setItem("local_potato_stage_requirement",potato_stage_requirements)
localStorage.setItem("local_achievements",achievements)
localStorage.setItem("local_auto_seeder",auto_seeder_unlocked)
localStorage.setItem("local_auto_planter",auto_planter_unlocked)
localStorage.setItem("local_auto_harvest",auto_harvest_unlocked)
localStorage.setItem("local_fertilizer_level",fertilizer_level)
localStorage.setItem("local_fertilizer_price",fertilizer_price)
localStorage.setItem("local_seed_research_cost",seed_research_cost)
localStorage.setItem("local_mashed_potatoes",mashed_potatoes)
localStorage.setItem("local_baked_potato_boost",baked_potato_boost)
localStorage.setItem("local_study_req",study_req)
localStorage.setItem("local_study_req_cost",study_req_cost)
console.log("game save changed")
console.log("please load save")
